#!/bin/bash
#
# [Ansible Role]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705 & Deiteq & FlickerRate
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
---
- name: Register Domain
  shell: "cat /var/plexguide/server.domain"
  register: domain
  ignore_errors: True

- name: Register IP
  shell: "cat /var/plexguide/server.ip"
  register: ipaddress
  ignore_errors: True

- name: Register Ports
  shell: "cat /var/plexguide/server.ports"
  register: ports
  ignore_errors: True

- name: Register HD Path
  shell: "cat /var/plexguide/server.hd.path"
  register: path
  ignore_errors: True

- name: Register Auth Path
  shell: "cat /var/plexguide/server.ht"
  register: auth
  ignore_errors: True

- name: "Register TLD"
  shell: "cat /var/plexguide/tld.program"
  register: toplevel
  ignore_errors: True

- name: Check Saved Image Path
  stat:
    path: "/var/plexguide/{{pgrole}}.image"
  register: storedpath

- name: "Register Saved Image"
  shell: "cat /var/plexguide/{{pgrole}}.image"
  register: tempimage
  when: storedpath.stat.exists

- name: Set to PLEX Local
  set_fact:
    image: "{{tempimage.stdout}}"
  when: storedpath.stat.exists

- name: Logging Ansible Role Information
  shell: "echo 'INFO - Ansible Role {{pgrole}} Started' > /var/plexguide/pg.log && bash /opt/plexguide/roles/log/log.sh"

- name: Remove {{pgrole}} Container
  docker_container:
    name: "{{pgrole}}"
    state: absent
  ignore_errors: True

- name: Storing Role Name
  shell: "echo '{{pgrole}}' > /tmp/program_var"
  ignore_errors: True

###### FOR TLD (START)
- debug: msg="Stored TLD - {{pgrole}} must match {{toplevel.stdout}} for TLD"

- name: "If Fact Matches - Enable TLD"
  set_fact:
    tldset: "{{domain.stdout}}"
  when: "toplevel.stdout == pgrole"

- debug: msg="TLDSET is now - {{tldset}}"
  when: "toplevel.stdout == pgrole"
###### FOR TLD (END)

###### FOR DEFAULT LABELS (START)

- name: Temp - Delete Bug Test"
  set_fact:
    tldset: ""

- name: Temp - Delete Bug Test"
  set_fact:
    authorization: "{{auth.stdout}}"

- name: "Set Default Labels - {{pgrole}}"
  set_fact:
    default_labels:
      traefik.enable: "true"
      traefik.frontend.auth.basic.users: "{{authorization}}"
      traefik.port: "{{intport}}"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:{{pgrole}}.{{domain.stdout}},{{tldset}}"
